services:
  mysql:
    image: mysql:8.0
    container_name: taskflow_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskflow_db
      MYSQL_USER: taskflow_user
      MYSQL_PASSWORD: taskflow_password
    ports:
      - "3307:3306"
    volumes:
      - taskflow_mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: taskflow_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  taskflow_mysql_data: